// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT COUNT(*) FROM api_keys WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAPIKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, user_id, name, key_hash, key_prefix, scope, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID        string
	UserID    string
	Name      string
	KeyHash   string
	KeyPrefix string
	Scope     string
	CreatedAt string
	ExpiresAt *string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scope,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, scope, created_at, last_used_at, expires_at, revoked_at FROM api_keys WHERE key_hash = ?
`

// The authentication lookup. Equality on an indexed hash, not on the secret:
// there is nothing here to compare in constant time, because the value in the
// WHERE clause is already a digest of the attacker's own input.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyForUser = `-- name: GetAPIKeyForUser :one
SELECT id, user_id, name, key_hash, key_prefix, scope, created_at, last_used_at, expires_at, revoked_at FROM api_keys WHERE id = ? AND user_id = ?
`

type GetAPIKeyForUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAPIKeyForUser(ctx context.Context, arg GetAPIKeyForUserParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyForUser, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, key_hash, key_prefix, scope, created_at, last_used_at, expires_at, revoked_at FROM api_keys
WHERE user_id = ? AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = ?
WHERE id = ? AND user_id = ? AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	RevokedAt *string
	ID        string
	UserID    string
}

// The user_id predicate is the ownership check: another user's key id matches
// zero rows rather than revoking their key.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, arg.RevokedAt, arg.ID, arg.UserID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type TouchAPIKeyLastUsedParams struct {
	LastUsedAt *string
	ID         string
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
