// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clubs.sql

package sqlc

import (
	"context"
)

const countActiveClubs = `-- name: CountActiveClubs :one
SELECT COUNT(*) FROM clubs WHERE user_id = ? AND active = 1
`

func (q *Queries) CountActiveClubs(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveClubs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClub = `-- name: CreateClub :exec
INSERT INTO clubs (
    id, user_id, club_type, label, brand, model, loft, shaft, flex, notes,
    expected_carry, average_dispersion,
    active, retired_at, display_order, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateClubParams struct {
	ID                string
	UserID            string
	ClubType          string
	Label             string
	Brand             *string
	Model             *string
	Loft              *float64
	Shaft             *string
	Flex              *string
	Notes             *string
	ExpectedCarry     *int64
	AverageDispersion *int64
	Active            int64
	RetiredAt         *string
	DisplayOrder      int64
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) error {
	_, err := q.db.ExecContext(ctx, createClub,
		arg.ID,
		arg.UserID,
		arg.ClubType,
		arg.Label,
		arg.Brand,
		arg.Model,
		arg.Loft,
		arg.Shaft,
		arg.Flex,
		arg.Notes,
		arg.ExpectedCarry,
		arg.AverageDispersion,
		arg.Active,
		arg.RetiredAt,
		arg.DisplayOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteClub = `-- name: DeleteClub :exec
DELETE FROM clubs WHERE id = ?
`

func (q *Queries) DeleteClub(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClub, id)
	return err
}

const getClub = `-- name: GetClub :one
SELECT id, user_id, club_type, label, brand, model, loft, shaft, flex, notes, active, retired_at, display_order, created_at, updated_at, expected_carry, average_dispersion FROM clubs WHERE id = ?
`

func (q *Queries) GetClub(ctx context.Context, id string) (Club, error) {
	row := q.db.QueryRowContext(ctx, getClub, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClubType,
		&i.Label,
		&i.Brand,
		&i.Model,
		&i.Loft,
		&i.Shaft,
		&i.Flex,
		&i.Notes,
		&i.Active,
		&i.RetiredAt,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectedCarry,
		&i.AverageDispersion,
	)
	return i, err
}

const listClubsByUser = `-- name: ListClubsByUser :many
SELECT id, user_id, club_type, label, brand, model, loft, shaft, flex, notes, active, retired_at, display_order, created_at, updated_at, expected_carry, average_dispersion FROM clubs
WHERE user_id = ?
ORDER BY display_order ASC, created_at ASC
`

func (q *Queries) ListClubsByUser(ctx context.Context, userID string) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, listClubsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Club{}
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClubType,
			&i.Label,
			&i.Brand,
			&i.Model,
			&i.Loft,
			&i.Shaft,
			&i.Flex,
			&i.Notes,
			&i.Active,
			&i.RetiredAt,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpectedCarry,
			&i.AverageDispersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxClubDisplayOrder = `-- name: MaxClubDisplayOrder :one
SELECT CAST(IFNULL(MAX(display_order), -1) AS INTEGER) AS max_order
FROM clubs WHERE user_id = ?
`

func (q *Queries) MaxClubDisplayOrder(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxClubDisplayOrder, userID)
	var max_order int64
	err := row.Scan(&max_order)
	return max_order, err
}

const setClubStatus = `-- name: SetClubStatus :exec
UPDATE clubs
SET active = ?, retired_at = ?, updated_at = ?
WHERE id = ?
`

type SetClubStatusParams struct {
	Active    int64
	RetiredAt *string
	UpdatedAt string
	ID        string
}

func (q *Queries) SetClubStatus(ctx context.Context, arg SetClubStatusParams) error {
	_, err := q.db.ExecContext(ctx, setClubStatus,
		arg.Active,
		arg.RetiredAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateClub = `-- name: UpdateClub :exec
UPDATE clubs
SET club_type = ?, label = ?, brand = ?, model = ?, loft = ?, shaft = ?,
    flex = ?, notes = ?, expected_carry = ?, average_dispersion = ?,
    display_order = ?, updated_at = ?
WHERE id = ?
`

type UpdateClubParams struct {
	ClubType          string
	Label             string
	Brand             *string
	Model             *string
	Loft              *float64
	Shaft             *string
	Flex              *string
	Notes             *string
	ExpectedCarry     *int64
	AverageDispersion *int64
	DisplayOrder      int64
	UpdatedAt         string
	ID                string
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) error {
	_, err := q.db.ExecContext(ctx, updateClub,
		arg.ClubType,
		arg.Label,
		arg.Brand,
		arg.Model,
		arg.Loft,
		arg.Shaft,
		arg.Flex,
		arg.Notes,
		arg.ExpectedCarry,
		arg.AverageDispersion,
		arg.DisplayOrder,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
