// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*) FROM courses
`

func (q *Queries) CountCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCourses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchCourses = `-- name: CountSearchCourses :one
SELECT COUNT(*) FROM courses
WHERE instr(lower(name), ?1) > 0
   OR instr(lower(IFNULL(address, '')), ?1) > 0
`

func (q *Queries) CountSearchCourses(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchCourses, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :exec
INSERT INTO courses (id, name, address, phone, website, notes, facility_type, latitude, longitude, pinned, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCourseParams struct {
	ID           string
	Name         string
	Address      *string
	Phone        *string
	Website      *string
	Notes        *string
	FacilityType *string
	Latitude     *float64
	Longitude    *float64
	Pinned       int64
	CreatedBy    string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Website,
		arg.Notes,
		arg.FacilityType,
		arg.Latitude,
		arg.Longitude,
		arg.Pinned,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, name, address, created_by, created_at, updated_at, phone, website, notes, facility_type, latitude, longitude, pinned FROM courses WHERE id = ?
`

func (q *Queries) GetCourse(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
		&i.Website,
		&i.Notes,
		&i.FacilityType,
		&i.Latitude,
		&i.Longitude,
		&i.Pinned,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, name, address, created_by, created_at, updated_at, phone, website, notes, facility_type, latitude, longitude, pinned FROM courses
ORDER BY name COLLATE NOCASE ASC
LIMIT ? OFFSET ?
`

type ListCoursesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Phone,
			&i.Website,
			&i.Notes,
			&i.FacilityType,
			&i.Latitude,
			&i.Longitude,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCourses = `-- name: SearchCourses :many
SELECT id, name, address, created_by, created_at, updated_at, phone, website, notes, facility_type, latitude, longitude, pinned FROM courses
WHERE instr(lower(name), ?1) > 0
   OR instr(lower(IFNULL(address, '')), ?1) > 0
ORDER BY name COLLATE NOCASE ASC
LIMIT ?3 OFFSET ?2
`

type SearchCoursesParams struct {
	Query  string
	Offset int64
	Limit  int64
}

// Search uses instr() rather than LIKE so the term is matched literally: a
// course named "50% Off Golf" is findable, and sqlc's SQLite parser does not
// support the ESCAPE clause that literal LIKE matching would require.
// lower() gives ASCII-case-insensitive matching; callers pass a lowered term.
func (q *Queries) SearchCourses(ctx context.Context, arg SearchCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, searchCourses, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Phone,
			&i.Website,
			&i.Notes,
			&i.FacilityType,
			&i.Latitude,
			&i.Longitude,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCourse = `-- name: TouchCourse :exec
UPDATE courses SET updated_at = ? WHERE id = ?
`

type TouchCourseParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) TouchCourse(ctx context.Context, arg TouchCourseParams) error {
	_, err := q.db.ExecContext(ctx, touchCourse, arg.UpdatedAt, arg.ID)
	return err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses SET name = ?, address = ?, phone = ?, website = ?, notes = ?, facility_type = ?, latitude = ?, longitude = ?, pinned = ?, updated_at = ? WHERE id = ?
`

type UpdateCourseParams struct {
	Name         string
	Address      *string
	Phone        *string
	Website      *string
	Notes        *string
	FacilityType *string
	Latitude     *float64
	Longitude    *float64
	Pinned       int64
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Website,
		arg.Notes,
		arg.FacilityType,
		arg.Latitude,
		arg.Longitude,
		arg.Pinned,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
