// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*) FROM courses
`

func (q *Queries) CountCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCourses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchCourses = `-- name: CountSearchCourses :one
SELECT COUNT(*) FROM courses
WHERE instr(lower(name), ?1) > 0
   OR instr(lower(IFNULL(street, '')), ?1) > 0
   OR instr(lower(IFNULL(city, '')), ?1) > 0
   OR instr(lower(IFNULL(region, '')), ?1) > 0
   OR instr(lower(IFNULL(postal_code, '')), ?1) > 0
   OR instr(lower(IFNULL(country, '')), ?1) > 0
`

func (q *Queries) CountSearchCourses(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchCourses, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :exec
INSERT INTO courses (id, name, street, city, region, postal_code, country, phone, website, notes, facility_type, latitude, longitude, pinned, uploaded_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCourseParams struct {
	ID           string
	Name         string
	Street       *string
	City         *string
	Region       *string
	PostalCode   *string
	Country      *string
	Phone        *string
	Website      *string
	Notes        *string
	FacilityType *string
	Latitude     *float64
	Longitude    *float64
	Pinned       int64
	UploadedBy   *string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Region,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.Website,
		arg.Notes,
		arg.FacilityType,
		arg.Latitude,
		arg.Longitude,
		arg.Pinned,
		arg.UploadedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, name, street, city, region, postal_code, country, latitude, longitude, phone, website, notes, facility_type, pinned, uploaded_by, created_at, updated_at FROM courses WHERE id = ?
`

func (q *Queries) GetCourse(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Region,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Notes,
		&i.FacilityType,
		&i.Pinned,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT courses.id, courses.name, courses.street, courses.city, courses.region, courses.postal_code, courses.country, courses.latitude, courses.longitude, courses.phone, courses.website, courses.notes, courses.facility_type, courses.pinned, courses.uploaded_by, courses.created_at, courses.updated_at FROM courses
LEFT JOIN users ON users.id = ?1 AND users.home_course_id = courses.id
ORDER BY (users.id IS NOT NULL) DESC, courses.pinned DESC, courses.name COLLATE NOCASE ASC
LIMIT ?3 OFFSET ?2
`

type ListCoursesParams struct {
	UserID string
	Offset int64
	Limit  int64
}

// The directory's one ordering, shared by the list and the search below.
//
// The caller's home course comes first, then pinned courses, then the rest by
// their names. It has to happen here rather than by re-sorting a page in the
// client: "first" across a paginated directory means first of all of them, and
// a client sort can only reach the twenty-five rows it was already sent.
//
// The home course is found by joining users rather than by comparing against a
// bound id, because sqlc's SQLite parser does not bind parameters inside an
// ORDER BY at all: it emits the placeholder but leaves it out of the params
// struct, so the remaining arguments silently shift by one. In a JOIN condition
// it binds correctly, and the join costs nothing extra: it reads the same
// home_course_id a separate lookup would have.
//
// The join matches at most one row and takes no column from it, so the result
// is still a plain course row. A player with no home course matches nothing,
// the first ordering term is false throughout, and the order falls through to
// pinned.
func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.City,
			&i.Region,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Website,
			&i.Notes,
			&i.FacilityType,
			&i.Pinned,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByUploader = `-- name: ListCoursesByUploader :many
SELECT id, name, street, city, region, postal_code, country, latitude, longitude, phone, website, notes, facility_type, pinned, uploaded_by, created_at, updated_at FROM courses
WHERE uploaded_by = ?
ORDER BY name COLLATE NOCASE ASC
`

// Every course this user uploaded, for the account export. Backed by
// idx_courses_uploaded_by.
func (q *Queries) ListCoursesByUploader(ctx context.Context, uploadedBy *string) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCoursesByUploader, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.City,
			&i.Region,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Website,
			&i.Notes,
			&i.FacilityType,
			&i.Pinned,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCourses = `-- name: SearchCourses :many
SELECT courses.id, courses.name, courses.street, courses.city, courses.region, courses.postal_code, courses.country, courses.latitude, courses.longitude, courses.phone, courses.website, courses.notes, courses.facility_type, courses.pinned, courses.uploaded_by, courses.created_at, courses.updated_at FROM courses
LEFT JOIN users ON users.id = ?1 AND users.home_course_id = courses.id
WHERE instr(lower(courses.name), ?2) > 0
   OR instr(lower(IFNULL(courses.street, '')), ?2) > 0
   OR instr(lower(IFNULL(courses.city, '')), ?2) > 0
   OR instr(lower(IFNULL(courses.region, '')), ?2) > 0
   OR instr(lower(IFNULL(courses.postal_code, '')), ?2) > 0
   OR instr(lower(IFNULL(courses.country, '')), ?2) > 0
ORDER BY (users.id IS NOT NULL) DESC, courses.pinned DESC, courses.name COLLATE NOCASE ASC
LIMIT ?4 OFFSET ?3
`

type SearchCoursesParams struct {
	UserID string
	Query  string
	Offset int64
	Limit  int64
}

// Search uses instr() rather than LIKE so the term is matched literally: a
// course named "50% Off Golf" is findable, and sqlc's SQLite parser does not
// support the ESCAPE clause that literal LIKE matching would require.
// lower() gives ASCII-case-insensitive matching; callers pass a lowered term.
//
// Every part of the address is searched, not just the street, so that "marne"
// and "MI" both find the courses there. That is what makes the profile's
// home-course picker usable: people look for their club by town, not by the
// street it sits on.
func (q *Queries) SearchCourses(ctx context.Context, arg SearchCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, searchCourses,
		arg.UserID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.City,
			&i.Region,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Website,
			&i.Notes,
			&i.FacilityType,
			&i.Pinned,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCourse = `-- name: TouchCourse :exec
UPDATE courses SET updated_at = ? WHERE id = ?
`

type TouchCourseParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) TouchCourse(ctx context.Context, arg TouchCourseParams) error {
	_, err := q.db.ExecContext(ctx, touchCourse, arg.UpdatedAt, arg.ID)
	return err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses SET name = ?, street = ?, city = ?, region = ?, postal_code = ?, country = ?, phone = ?, website = ?, notes = ?, facility_type = ?, latitude = ?, longitude = ?, pinned = ?, updated_at = ? WHERE id = ?
`

type UpdateCourseParams struct {
	Name         string
	Street       *string
	City         *string
	Region       *string
	PostalCode   *string
	Country      *string
	Phone        *string
	Website      *string
	Notes        *string
	FacilityType *string
	Latitude     *float64
	Longitude    *float64
	Pinned       int64
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Region,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.Website,
		arg.Notes,
		arg.FacilityType,
		arg.Latitude,
		arg.Longitude,
		arg.Pinned,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
