// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_removal_requests.sql

package sqlc

import (
	"context"
)

const countPendingRemovalRequestsForCourse = `-- name: CountPendingRemovalRequestsForCourse :one
SELECT COUNT(*) FROM course_removal_requests
WHERE course_id = ? AND resolved_at IS NULL
`

// Guards against a second request for a course that already has one waiting.
func (q *Queries) CountPendingRemovalRequestsForCourse(ctx context.Context, courseID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingRemovalRequestsForCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourseRemovalRequest = `-- name: CreateCourseRemovalRequest :exec
INSERT INTO course_removal_requests (id, course_id, course_name, requested_by, reason, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCourseRemovalRequestParams struct {
	ID          string
	CourseID    *string
	CourseName  string
	RequestedBy *string
	Reason      string
	CreatedAt   string
}

func (q *Queries) CreateCourseRemovalRequest(ctx context.Context, arg CreateCourseRemovalRequestParams) error {
	_, err := q.db.ExecContext(ctx, createCourseRemovalRequest,
		arg.ID,
		arg.CourseID,
		arg.CourseName,
		arg.RequestedBy,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const getCourseRemovalRequest = `-- name: GetCourseRemovalRequest :one
SELECT id, course_id, course_name, requested_by, reason, created_at, resolved_at, resolution FROM course_removal_requests WHERE id = ?
`

func (q *Queries) GetCourseRemovalRequest(ctx context.Context, id string) (CourseRemovalRequest, error) {
	row := q.db.QueryRowContext(ctx, getCourseRemovalRequest, id)
	var i CourseRemovalRequest
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CourseName,
		&i.RequestedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const listPendingCourseRemovalRequests = `-- name: ListPendingCourseRemovalRequests :many
SELECT r.id, r.course_id, r.course_name, r.requested_by, r.reason, r.created_at, r.resolved_at, r.resolution, u.display_name AS requested_by_name
FROM course_removal_requests r
LEFT JOIN users u ON u.id = r.requested_by
WHERE r.resolved_at IS NULL
ORDER BY r.created_at ASC
`

type ListPendingCourseRemovalRequestsRow struct {
	ID              string
	CourseID        *string
	CourseName      string
	RequestedBy     *string
	Reason          string
	CreatedAt       string
	ResolvedAt      *string
	Resolution      *string
	RequestedByName *string
}

// The administrator's queue. Joined out to the requester's display name so the
// page does not have to resolve each one, and left-joined because a requester
// may since have deleted their account.
func (q *Queries) ListPendingCourseRemovalRequests(ctx context.Context) ([]ListPendingCourseRemovalRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCourseRemovalRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCourseRemovalRequestsRow{}
	for rows.Next() {
		var i ListPendingCourseRemovalRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.CourseName,
			&i.RequestedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Resolution,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCourseRemovalRequest = `-- name: ResolveCourseRemovalRequest :exec
UPDATE course_removal_requests
SET resolved_at = ?, resolution = ?
WHERE id = ? AND resolved_at IS NULL
`

type ResolveCourseRemovalRequestParams struct {
	ResolvedAt *string
	Resolution *string
	ID         string
}

func (q *Queries) ResolveCourseRemovalRequest(ctx context.Context, arg ResolveCourseRemovalRequestParams) error {
	_, err := q.db.ExecContext(ctx, resolveCourseRemovalRequest, arg.ResolvedAt, arg.Resolution, arg.ID)
	return err
}
