// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_challenges.sql

package sqlc

import (
	"context"
)

const consumeEmailChallenge = `-- name: ConsumeEmailChallenge :exec
UPDATE email_challenges SET consumed_at = ? WHERE id = ? AND consumed_at IS NULL
`

type ConsumeEmailChallengeParams struct {
	ConsumedAt *string
	ID         string
}

func (q *Queries) ConsumeEmailChallenge(ctx context.Context, arg ConsumeEmailChallengeParams) error {
	_, err := q.db.ExecContext(ctx, consumeEmailChallenge, arg.ConsumedAt, arg.ID)
	return err
}

const consumeOutstandingEmailChallenges = `-- name: ConsumeOutstandingEmailChallenges :exec
UPDATE email_challenges
SET consumed_at = ?
WHERE user_id = ? AND purpose = ? AND consumed_at IS NULL
`

type ConsumeOutstandingEmailChallengesParams struct {
	ConsumedAt *string
	UserID     string
	Purpose    string
}

// Invalidates whatever is outstanding. Issuing a new code has to retire the old
// one, or every resend widens the set of codes that would be accepted.
func (q *Queries) ConsumeOutstandingEmailChallenges(ctx context.Context, arg ConsumeOutstandingEmailChallengesParams) error {
	_, err := q.db.ExecContext(ctx, consumeOutstandingEmailChallenges, arg.ConsumedAt, arg.UserID, arg.Purpose)
	return err
}

const countRecentEmailChallenges = `-- name: CountRecentEmailChallenges :one
SELECT COUNT(*) FROM email_challenges
WHERE user_id = ? AND purpose = ? AND created_at > ?
`

type CountRecentEmailChallengesParams struct {
	UserID    string
	Purpose   string
	CreatedAt string
}

// Counts what has been sent to one user for one purpose since a cut-off. This
// is the send-side rate limit: without it, "resend the code" is an open relay
// pointed at somebody else's inbox.
func (q *Queries) CountRecentEmailChallenges(ctx context.Context, arg CountRecentEmailChallengesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentEmailChallenges, arg.UserID, arg.Purpose, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailChallenge = `-- name: CreateEmailChallenge :exec
INSERT INTO email_challenges (id, user_id, purpose, email, code_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEmailChallengeParams struct {
	ID        string
	UserID    string
	Purpose   string
	Email     string
	CodeHash  string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) CreateEmailChallenge(ctx context.Context, arg CreateEmailChallengeParams) error {
	_, err := q.db.ExecContext(ctx, createEmailChallenge,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredEmailChallenges = `-- name: DeleteExpiredEmailChallenges :exec
DELETE FROM email_challenges WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredEmailChallenges(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEmailChallenges, expiresAt)
	return err
}

const getEmailChallenge = `-- name: GetEmailChallenge :one
SELECT id, user_id, purpose, email, code_hash, attempts, expires_at, consumed_at, created_at FROM email_challenges WHERE id = ?
`

func (q *Queries) GetEmailChallenge(ctx context.Context, id string) (EmailChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailChallenge, id)
	var i EmailChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailChallengeByCodeHash = `-- name: GetEmailChallengeByCodeHash :one
SELECT id, user_id, purpose, email, code_hash, attempts, expires_at, consumed_at, created_at FROM email_challenges WHERE code_hash = ? AND purpose = ?
`

type GetEmailChallengeByCodeHashParams struct {
	CodeHash string
	Purpose  string
}

// The verification link carries the token itself rather than a challenge id, so
// this is the only lookup that starts from the hash. Two-factor never uses it:
// six digits are not unique enough to name a row.
func (q *Queries) GetEmailChallengeByCodeHash(ctx context.Context, arg GetEmailChallengeByCodeHashParams) (EmailChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailChallengeByCodeHash, arg.CodeHash, arg.Purpose)
	var i EmailChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmailChallengeAttempts = `-- name: IncrementEmailChallengeAttempts :exec
UPDATE email_challenges SET attempts = attempts + 1 WHERE id = ?
`

func (q *Queries) IncrementEmailChallengeAttempts(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementEmailChallengeAttempts, id)
	return err
}
