// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holes.sql

package sqlc

import (
	"context"
)

const createHole = `-- name: CreateHole :exec
INSERT INTO holes (id, course_id, hole_number, handicap_index)
VALUES (?, ?, ?, ?)
`

type CreateHoleParams struct {
	ID            string
	CourseID      string
	HoleNumber    int64
	HandicapIndex *int64
}

func (q *Queries) CreateHole(ctx context.Context, arg CreateHoleParams) error {
	_, err := q.db.ExecContext(ctx, createHole,
		arg.ID,
		arg.CourseID,
		arg.HoleNumber,
		arg.HandicapIndex,
	)
	return err
}

const deleteHole = `-- name: DeleteHole :exec
DELETE FROM holes WHERE id = ?
`

func (q *Queries) DeleteHole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHole, id)
	return err
}

const deleteHoleTeeDetail = `-- name: DeleteHoleTeeDetail :exec
DELETE FROM hole_tee_details WHERE hole_id = ? AND tee_id = ?
`

type DeleteHoleTeeDetailParams struct {
	HoleID string
	TeeID  string
}

func (q *Queries) DeleteHoleTeeDetail(ctx context.Context, arg DeleteHoleTeeDetailParams) error {
	_, err := q.db.ExecContext(ctx, deleteHoleTeeDetail, arg.HoleID, arg.TeeID)
	return err
}

const getHole = `-- name: GetHole :one
SELECT id, course_id, hole_number, handicap_index FROM holes WHERE id = ?
`

func (q *Queries) GetHole(ctx context.Context, id string) (Hole, error) {
	row := q.db.QueryRowContext(ctx, getHole, id)
	var i Hole
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.HoleNumber,
		&i.HandicapIndex,
	)
	return i, err
}

const getHoleByNumber = `-- name: GetHoleByNumber :one
SELECT id, course_id, hole_number, handicap_index FROM holes WHERE course_id = ? AND hole_number = ?
`

type GetHoleByNumberParams struct {
	CourseID   string
	HoleNumber int64
}

func (q *Queries) GetHoleByNumber(ctx context.Context, arg GetHoleByNumberParams) (Hole, error) {
	row := q.db.QueryRowContext(ctx, getHoleByNumber, arg.CourseID, arg.HoleNumber)
	var i Hole
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.HoleNumber,
		&i.HandicapIndex,
	)
	return i, err
}

const getHoleTeeDetail = `-- name: GetHoleTeeDetail :one
SELECT id, hole_id, tee_id, par, yardage FROM hole_tee_details WHERE hole_id = ? AND tee_id = ?
`

type GetHoleTeeDetailParams struct {
	HoleID string
	TeeID  string
}

func (q *Queries) GetHoleTeeDetail(ctx context.Context, arg GetHoleTeeDetailParams) (HoleTeeDetail, error) {
	row := q.db.QueryRowContext(ctx, getHoleTeeDetail, arg.HoleID, arg.TeeID)
	var i HoleTeeDetail
	err := row.Scan(
		&i.ID,
		&i.HoleID,
		&i.TeeID,
		&i.Par,
		&i.Yardage,
	)
	return i, err
}

const listHoleTeeDetailsByCourse = `-- name: ListHoleTeeDetailsByCourse :many
SELECT d.id, d.hole_id, d.tee_id, d.par, d.yardage FROM hole_tee_details d
JOIN holes h ON h.id = d.hole_id
WHERE h.course_id = ?
ORDER BY h.hole_number ASC
`

func (q *Queries) ListHoleTeeDetailsByCourse(ctx context.Context, courseID string) ([]HoleTeeDetail, error) {
	rows, err := q.db.QueryContext(ctx, listHoleTeeDetailsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoleTeeDetail{}
	for rows.Next() {
		var i HoleTeeDetail
		if err := rows.Scan(
			&i.ID,
			&i.HoleID,
			&i.TeeID,
			&i.Par,
			&i.Yardage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoleTeeDetailsByHole = `-- name: ListHoleTeeDetailsByHole :many
SELECT id, hole_id, tee_id, par, yardage FROM hole_tee_details WHERE hole_id = ?
`

func (q *Queries) ListHoleTeeDetailsByHole(ctx context.Context, holeID string) ([]HoleTeeDetail, error) {
	rows, err := q.db.QueryContext(ctx, listHoleTeeDetailsByHole, holeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoleTeeDetail{}
	for rows.Next() {
		var i HoleTeeDetail
		if err := rows.Scan(
			&i.ID,
			&i.HoleID,
			&i.TeeID,
			&i.Par,
			&i.Yardage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoleTeeDetailsByUploader = `-- name: ListHoleTeeDetailsByUploader :many
SELECT d.id, d.hole_id, d.tee_id, d.par, d.yardage FROM hole_tee_details d
JOIN holes h ON h.id = d.hole_id
JOIN courses c ON c.id = h.course_id
WHERE c.uploaded_by = ?
ORDER BY h.course_id ASC, h.hole_number ASC
`

func (q *Queries) ListHoleTeeDetailsByUploader(ctx context.Context, uploadedBy *string) ([]HoleTeeDetail, error) {
	rows, err := q.db.QueryContext(ctx, listHoleTeeDetailsByUploader, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoleTeeDetail{}
	for rows.Next() {
		var i HoleTeeDetail
		if err := rows.Scan(
			&i.ID,
			&i.HoleID,
			&i.TeeID,
			&i.Par,
			&i.Yardage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolesByCourse = `-- name: ListHolesByCourse :many
SELECT id, course_id, hole_number, handicap_index FROM holes WHERE course_id = ? ORDER BY hole_number ASC
`

func (q *Queries) ListHolesByCourse(ctx context.Context, courseID string) ([]Hole, error) {
	rows, err := q.db.QueryContext(ctx, listHolesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hole{}
	for rows.Next() {
		var i Hole
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.HoleNumber,
			&i.HandicapIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolesByUploader = `-- name: ListHolesByUploader :many
SELECT h.id, h.course_id, h.hole_number, h.handicap_index FROM holes h
JOIN courses c ON c.id = h.course_id
WHERE c.uploaded_by = ?
ORDER BY h.course_id ASC, h.hole_number ASC
`

// Uploader-scoped bulk reads for the account export. See ListTeesByUploader.
func (q *Queries) ListHolesByUploader(ctx context.Context, uploadedBy *string) ([]Hole, error) {
	rows, err := q.db.QueryContext(ctx, listHolesByUploader, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hole{}
	for rows.Next() {
		var i Hole
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.HoleNumber,
			&i.HandicapIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTeeYardage = `-- name: SumTeeYardage :one
SELECT CAST(IFNULL(SUM(yardage), 0) AS INTEGER) AS total FROM hole_tee_details WHERE tee_id = ?
`

func (q *Queries) SumTeeYardage(ctx context.Context, teeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumTeeYardage, teeID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateHole = `-- name: UpdateHole :exec
UPDATE holes SET handicap_index = ? WHERE id = ?
`

type UpdateHoleParams struct {
	HandicapIndex *int64
	ID            string
}

func (q *Queries) UpdateHole(ctx context.Context, arg UpdateHoleParams) error {
	_, err := q.db.ExecContext(ctx, updateHole, arg.HandicapIndex, arg.ID)
	return err
}

const upsertHoleTeeDetail = `-- name: UpsertHoleTeeDetail :exec
INSERT INTO hole_tee_details (id, hole_id, tee_id, par, yardage)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(hole_id, tee_id) DO UPDATE SET par = excluded.par, yardage = excluded.yardage
`

type UpsertHoleTeeDetailParams struct {
	ID      string
	HoleID  string
	TeeID   string
	Par     int64
	Yardage int64
}

func (q *Queries) UpsertHoleTeeDetail(ctx context.Context, arg UpsertHoleTeeDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertHoleTeeDetail,
		arg.ID,
		arg.HoleID,
		arg.TeeID,
		arg.Par,
		arg.Yardage,
	)
	return err
}
