// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type ApiKey struct {
	ID         string
	UserID     string
	Name       string
	KeyHash    string
	KeyPrefix  string
	Scope      string
	CreatedAt  string
	LastUsedAt *string
	ExpiresAt  *string
	RevokedAt  *string
}

type Club struct {
	ID                string
	UserID            string
	ClubType          string
	Label             string
	Brand             *string
	Model             *string
	Loft              *float64
	Shaft             *string
	Flex              *string
	Notes             *string
	ExpectedCarry     *int64
	AverageDispersion *int64
	Active            int64
	RetiredAt         *string
	DisplayOrder      int64
	CreatedAt         string
	UpdatedAt         string
}

type Course struct {
	ID           string
	Name         string
	Street       *string
	City         *string
	Region       *string
	PostalCode   *string
	Country      *string
	Latitude     *float64
	Longitude    *float64
	Phone        *string
	Website      *string
	Notes        *string
	FacilityType *string
	Pinned       int64
	UploadedBy   *string
	CreatedAt    string
	UpdatedAt    string
}

type CourseRemovalRequest struct {
	ID          string
	CourseID    *string
	CourseName  string
	RequestedBy *string
	Reason      string
	CreatedAt   string
	ResolvedAt  *string
	Resolution  *string
}

type EmailChallenge struct {
	ID         string
	UserID     string
	Purpose    string
	Email      string
	CodeHash   string
	Attempts   int64
	ExpiresAt  string
	ConsumedAt *string
	CreatedAt  string
}

type Hole struct {
	ID            string
	CourseID      string
	HoleNumber    int64
	HandicapIndex *int64
}

type HoleTeeDetail struct {
	ID      string
	HoleID  string
	TeeID   string
	Par     int64
	Yardage int64
}

type OauthAccount struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	ProviderEmail   *string
	CreatedAt       string
}

type RecoveryCode struct {
	ID         string
	UserID     string
	CodeHash   string
	CreatedAt  string
	ConsumedAt *string
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt string
	CreatedAt string
	RevokedAt *string
}

type Round struct {
	ID            string
	UserID        string
	CourseID      *string
	CourseName    string
	TeeID         *string
	TeeName       string
	TeeColor      *string
	CourseRating  *float64
	SlopeRating   *int64
	PlayedOn      string
	StartedAt     *string
	CompletedAt   *string
	Status        string
	EntryMode     string
	HolesIntended int64
	Nine          *string
	Notes         *string
	CreatedAt     string
	UpdatedAt     string
}

type RoundHole struct {
	ID              string
	RoundID         string
	HoleNumber      int64
	Par             *int64
	Yardage         *int64
	StrokeIndex     *int64
	Strokes         *int64
	Putts           *int64
	TeeClubID       *string
	TeeAccuracy     *string
	FirstPuttFeet   *int64
	FairwayBunker   int64
	GreensideBunker int64
	Penalties       int64
	PenaltyType     *string
}

type Tee struct {
	ID                      string
	CourseID                string
	Name                    string
	Color                   string
	CourseRatingMen         *float64
	SlopeRatingMen          *int64
	CourseRatingWomen       *float64
	SlopeRatingWomen        *int64
	Front9CourseRatingMen   *float64
	Front9SlopeRatingMen    *int64
	Back9CourseRatingMen    *float64
	Back9SlopeRatingMen     *int64
	Front9CourseRatingWomen *float64
	Front9SlopeRatingWomen  *int64
	Back9CourseRatingWomen  *float64
	Back9SlopeRatingWomen   *int64
	DisplayOrder            int64
}

type TrustedDevice struct {
	ID         string
	UserID     string
	TokenHash  string
	Label      *string
	ExpiresAt  string
	CreatedAt  string
	LastUsedAt *string
}

type User struct {
	ID              string
	Email           string
	PasswordHash    *string
	DisplayName     string
	EmailVerified   int64
	TwoFactorEmail  int64
	FirstName       *string
	LastName        *string
	AvatarKey       *string
	HomeCourseID    *string
	LocationCity    *string
	LocationRegion  *string
	LocationCountry *string
	DistanceUnit    string
	CreatedAt       string
	UpdatedAt       string
	Gender          *string
}

type UserAvatar struct {
	UserID      string
	Image       []byte
	ContentType string
	ByteSize    int64
	UpdatedAt   string
}
