// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type ApiKey struct {
	ID         string
	UserID     string
	Name       string
	KeyHash    string
	KeyPrefix  string
	Scope      string
	CreatedAt  string
	LastUsedAt *string
	ExpiresAt  *string
	RevokedAt  *string
}

type Club struct {
	ID                string
	UserID            string
	ClubType          string
	Label             string
	Brand             *string
	Model             *string
	Loft              *float64
	Shaft             *string
	Flex              *string
	Notes             *string
	Active            int64
	RetiredAt         *string
	DisplayOrder      int64
	CreatedAt         string
	UpdatedAt         string
	ExpectedCarry     *int64
	AverageDispersion *int64
}

type Course struct {
	ID           string
	Name         string
	Address      *string
	CreatedBy    string
	CreatedAt    string
	UpdatedAt    string
	Phone        *string
	Website      *string
	Notes        *string
	FacilityType *string
	Latitude     *float64
	Longitude    *float64
	Pinned       int64
}

type Hole struct {
	ID            string
	CourseID      string
	HoleNumber    int64
	HandicapIndex *int64
}

type HoleTeeDetail struct {
	ID      string
	HoleID  string
	TeeID   string
	Par     int64
	Yardage int64
}

type OauthAccount struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	ProviderEmail   *string
	CreatedAt       string
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt string
	CreatedAt string
	RevokedAt *string
}

type Tee struct {
	ID                      string
	CourseID                string
	Name                    string
	Color                   string
	CourseRatingMen         *float64
	SlopeRatingMen          *int64
	TotalYardage            *int64
	DisplayOrder            int64
	CourseRatingWomen       *float64
	SlopeRatingWomen        *int64
	Front9CourseRatingMen   *float64
	Front9SlopeRatingMen    *int64
	Back9CourseRatingMen    *float64
	Back9SlopeRatingMen     *int64
	Front9CourseRatingWomen *float64
	Front9SlopeRatingWomen  *int64
	Back9CourseRatingWomen  *float64
	Back9SlopeRatingWomen   *int64
}

type User struct {
	ID              string
	Email           string
	PasswordHash    *string
	DisplayName     string
	EmailVerified   int64
	CreatedAt       string
	DistanceUnit    string
	FirstName       *string
	LastName        *string
	AvatarKey       *string
	HomeCourseID    *string
	LocationCity    *string
	LocationRegion  *string
	LocationCountry *string
	UpdatedAt       string
}

type UserAvatar struct {
	UserID      string
	Image       []byte
	ContentType string
	ByteSize    int64
	UpdatedAt   string
}
