// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Course struct {
	ID        string
	Name      string
	Address   *string
	CreatedBy string
	CreatedAt string
	UpdatedAt string
}

type Hole struct {
	ID            string
	CourseID      string
	HoleNumber    int64
	HandicapIndex *int64
}

type HoleTeeDetail struct {
	ID      string
	HoleID  string
	TeeID   string
	Par     int64
	Yardage int64
}

type OauthAccount struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	ProviderEmail   *string
	CreatedAt       string
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt string
	CreatedAt string
	RevokedAt *string
}

type Tee struct {
	ID           string
	CourseID     string
	Name         string
	Color        string
	CourseRating *float64
	SlopeRating  *int64
	TotalYardage *int64
	DisplayOrder int64
}

type User struct {
	ID            string
	Email         string
	PasswordHash  *string
	DisplayName   string
	EmailVerified int64
	CreatedAt     string
}
