// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package sqlc

import (
	"context"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (id, user_id, provider, provider_subject, provider_email, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOAuthAccountParams struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	ProviderEmail   *string
	CreatedAt       string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.ProviderEmail,
		arg.CreatedAt,
	)
	return err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :exec
DELETE FROM oauth_accounts WHERE user_id = ? AND provider = ?
`

type DeleteOAuthAccountParams struct {
	UserID   string
	Provider string
}

func (q *Queries) DeleteOAuthAccount(ctx context.Context, arg DeleteOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthAccount, arg.UserID, arg.Provider)
	return err
}

const getOAuthAccountByProviderSubject = `-- name: GetOAuthAccountByProviderSubject :one
SELECT id, user_id, provider, provider_subject, provider_email, created_at FROM oauth_accounts WHERE provider = ? AND provider_subject = ?
`

type GetOAuthAccountByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetOAuthAccountByProviderSubject(ctx context.Context, arg GetOAuthAccountByProviderSubjectParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.ProviderEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthAccountsByUser = `-- name: ListOAuthAccountsByUser :many
SELECT id, user_id, provider, provider_subject, provider_email, created_at FROM oauth_accounts WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) ListOAuthAccountsByUser(ctx context.Context, userID string) ([]OauthAccount, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.ProviderEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
