// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountActiveAPIKeys(ctx context.Context, userID string) (int64, error)
	CountActiveClubs(ctx context.Context, userID string) (int64, error)
	CountCourses(ctx context.Context) (int64, error)
	// Guards against a second request for a course that already has one waiting.
	CountPendingRemovalRequestsForCourse(ctx context.Context, courseID *string) (int64, error)
	CountSearchCourses(ctx context.Context, query string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateClub(ctx context.Context, arg CreateClubParams) error
	CreateCourse(ctx context.Context, arg CreateCourseParams) error
	CreateCourseRemovalRequest(ctx context.Context, arg CreateCourseRemovalRequestParams) error
	CreateHole(ctx context.Context, arg CreateHoleParams) error
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateTee(ctx context.Context, arg CreateTeeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteClub(ctx context.Context, id string) error
	DeleteCourse(ctx context.Context, id string) error
	DeleteExpiredRefreshTokens(ctx context.Context, expiresAt string) error
	DeleteHole(ctx context.Context, id string) error
	DeleteHoleTeeDetail(ctx context.Context, arg DeleteHoleTeeDetailParams) error
	DeleteOAuthAccount(ctx context.Context, arg DeleteOAuthAccountParams) error
	DeleteTee(ctx context.Context, id string) error
	DeleteUserAvatar(ctx context.Context, userID string) error
	// The authentication lookup. Equality on an indexed hash, not on the secret:
	// there is nothing here to compare in constant time, because the value in the
	// WHERE clause is already a digest of the attacker's own input.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyForUser(ctx context.Context, arg GetAPIKeyForUserParams) (ApiKey, error)
	// The whole avatar serve path, in one indexed lookup. Joined rather than keyed
	// directly on the image row so that the unguessable key stays in one place.
	GetAvatarByKey(ctx context.Context, avatarKey *string) (GetAvatarByKeyRow, error)
	GetAvatarByUser(ctx context.Context, userID string) (UserAvatar, error)
	GetClub(ctx context.Context, id string) (Club, error)
	GetCourse(ctx context.Context, id string) (Course, error)
	GetCourseRemovalRequest(ctx context.Context, id string) (CourseRemovalRequest, error)
	GetHole(ctx context.Context, id string) (Hole, error)
	GetHoleByNumber(ctx context.Context, arg GetHoleByNumberParams) (Hole, error)
	GetHoleTeeDetail(ctx context.Context, arg GetHoleTeeDetailParams) (HoleTeeDetail, error)
	GetOAuthAccountByProviderSubject(ctx context.Context, arg GetOAuthAccountByProviderSubjectParams) (OauthAccount, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTee(ctx context.Context, id string) (Tee, error)
	GetTeeByName(ctx context.Context, arg GetTeeByNameParams) (Tee, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error)
	ListClubsByUser(ctx context.Context, userID string) ([]Club, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	// Every course this user uploaded, for the account export. Backed by
	// idx_courses_uploaded_by.
	ListCoursesByUploader(ctx context.Context, uploadedBy *string) ([]Course, error)
	ListHoleTeeDetailsByCourse(ctx context.Context, courseID string) ([]HoleTeeDetail, error)
	ListHoleTeeDetailsByHole(ctx context.Context, holeID string) ([]HoleTeeDetail, error)
	ListHoleTeeDetailsByUploader(ctx context.Context, uploadedBy *string) ([]HoleTeeDetail, error)
	ListHolesByCourse(ctx context.Context, courseID string) ([]Hole, error)
	// Uploader-scoped bulk reads for the account export. See ListTeesByUploader.
	ListHolesByUploader(ctx context.Context, uploadedBy *string) ([]Hole, error)
	ListOAuthAccountsByUser(ctx context.Context, userID string) ([]OauthAccount, error)
	// The administrator's queue. Joined out to the requester's display name so the
	// page does not have to resolve each one, and left-joined because a requester
	// may since have deleted their account.
	ListPendingCourseRemovalRequests(ctx context.Context) ([]ListPendingCourseRemovalRequestsRow, error)
	ListTeesByCourse(ctx context.Context, courseID string) ([]Tee, error)
	// Uploader-scoped bulk read for the account export. Reading per course instead
	// would cost three queries each, which on a single-connection pool turns a
	// sixty-course export into a hundred and eighty sequential round trips.
	// Ordering by course_id first lets the caller group in one pass.
	ListTeesByUploader(ctx context.Context, uploadedBy *string) ([]Tee, error)
	MaxClubDisplayOrder(ctx context.Context, userID string) (int64, error)
	MaxTeeDisplayOrder(ctx context.Context, courseID string) (int64, error)
	ResolveCourseRemovalRequest(ctx context.Context, arg ResolveCourseRemovalRequestParams) error
	// The user_id predicate is the ownership check: another user's key id matches
	// zero rows rather than revoking their key.
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// Search uses instr() rather than LIKE so the term is matched literally: a
	// course named "50% Off Golf" is findable, and sqlc's SQLite parser does not
	// support the ESCAPE clause that literal LIKE matching would require.
	// lower() gives ASCII-case-insensitive matching; callers pass a lowered term.
	SearchCourses(ctx context.Context, arg SearchCoursesParams) ([]Course, error)
	SetClubStatus(ctx context.Context, arg SetClubStatusParams) error
	SetUserAvatarKey(ctx context.Context, arg SetUserAvatarKeyParams) error
	SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	SumTeeYardage(ctx context.Context, teeID string) (int64, error)
	TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error
	TouchCourse(ctx context.Context, arg TouchCourseParams) error
	UpdateClub(ctx context.Context, arg UpdateClubParams) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	UpdateHole(ctx context.Context, arg UpdateHoleParams) error
	UpdateTee(ctx context.Context, arg UpdateTeeParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserDistanceUnit(ctx context.Context, arg UpdateUserDistanceUnitParams) error
	// Changing an address always drops verification: the new one has not been
	// proven, and carrying the old flag over would mark an unproven address
	// verified.
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertHoleTeeDetail(ctx context.Context, arg UpsertHoleTeeDetailParams) error
	UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) error
}

var _ Querier = (*Queries)(nil)
