// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package sqlc

import (
	"context"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :exec
UPDATE recovery_codes SET consumed_at = ? WHERE id = ? AND consumed_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	ConsumedAt *string
	ID         string
}

// Guarded on consumed_at IS NULL so two requests racing the same code cannot
// both come away having spent it.
func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, consumeRecoveryCode, arg.ConsumedAt, arg.ID)
	return err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM recovery_codes WHERE user_id = ? AND consumed_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_codes (id, user_id, code_hash, created_at)
VALUES (?, ?, ?, ?)
`

type CreateRecoveryCodeParams struct {
	ID        string
	UserID    string
	CodeHash  string
	CreatedAt string
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.CreatedAt,
	)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = ?
`

// Regenerating replaces the whole set rather than topping it up: a sheet that
// is partly old and partly new is one nobody can reason about.
func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, user_id, code_hash, created_at, consumed_at FROM recovery_codes
WHERE user_id = ? AND consumed_at IS NULL
ORDER BY created_at
`

// Returns the hashes to check a submitted code against. There is no lookup by
// hash: argon2id salts every hash, so the same code stored twice hashes
// differently and only a scan can match it.
func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID string) ([]RecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.CreatedAt,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
