// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rounds.sql

package sqlc

import (
	"context"
)

const countRoundHolesByClub = `-- name: CountRoundHolesByClub :one
SELECT COUNT(*) FROM round_holes WHERE tee_club_id = ?
`

// Guards DELETE /clubs/{id}. A club that has been played has to keep its row,
// or the rounds played with it lose the only record of what was in hand.
func (q *Queries) CountRoundHolesByClub(ctx context.Context, teeClubID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoundHolesByClub, teeClubID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRounds = `-- name: CountRounds :one
SELECT COUNT(*) FROM rounds WHERE user_id = ?
`

func (q *Queries) CountRounds(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRounds, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRound = `-- name: CreateRound :exec
INSERT INTO rounds (
    id, user_id, course_id, course_name, tee_id, tee_name, tee_color,
    course_rating, slope_rating, played_on, started_at, status, entry_mode,
    holes_intended, nine, notes, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRoundParams struct {
	ID            string
	UserID        string
	CourseID      *string
	CourseName    string
	TeeID         *string
	TeeName       string
	TeeColor      *string
	CourseRating  *float64
	SlopeRating   *int64
	PlayedOn      string
	StartedAt     *string
	Status        string
	EntryMode     string
	HolesIntended int64
	Nine          *string
	Notes         *string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) error {
	_, err := q.db.ExecContext(ctx, createRound,
		arg.ID,
		arg.UserID,
		arg.CourseID,
		arg.CourseName,
		arg.TeeID,
		arg.TeeName,
		arg.TeeColor,
		arg.CourseRating,
		arg.SlopeRating,
		arg.PlayedOn,
		arg.StartedAt,
		arg.Status,
		arg.EntryMode,
		arg.HolesIntended,
		arg.Nine,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRound = `-- name: DeleteRound :exec
DELETE FROM rounds WHERE id = ? AND user_id = ?
`

type DeleteRoundParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteRound(ctx context.Context, arg DeleteRoundParams) error {
	_, err := q.db.ExecContext(ctx, deleteRound, arg.ID, arg.UserID)
	return err
}

const deleteRoundHole = `-- name: DeleteRoundHole :exec
DELETE FROM round_holes WHERE round_id = ? AND hole_number = ?
`

type DeleteRoundHoleParams struct {
	RoundID    string
	HoleNumber int64
}

func (q *Queries) DeleteRoundHole(ctx context.Context, arg DeleteRoundHoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoundHole, arg.RoundID, arg.HoleNumber)
	return err
}

const getRound = `-- name: GetRound :one
SELECT id, user_id, course_id, course_name, tee_id, tee_name, tee_color, course_rating, slope_rating, played_on, started_at, completed_at, status, entry_mode, holes_intended, nine, notes, created_at, updated_at FROM rounds WHERE id = ? AND user_id = ?
`

type GetRoundParams struct {
	ID     string
	UserID string
}

// Scoped by user on every read. Another player's round id returns no rows,
// which the service turns into a 404 rather than a 403: confirming that an id
// exists leaks more than the refusal is worth. Same rule as the golf bag.
func (q *Queries) GetRound(ctx context.Context, arg GetRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, arg.ID, arg.UserID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.CourseName,
		&i.TeeID,
		&i.TeeName,
		&i.TeeColor,
		&i.CourseRating,
		&i.SlopeRating,
		&i.PlayedOn,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.EntryMode,
		&i.HolesIntended,
		&i.Nine,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRoundHolesByUser = `-- name: ListAllRoundHolesByUser :many
SELECT round_holes.id, round_holes.round_id, round_holes.hole_number, round_holes.par, round_holes.yardage, round_holes.stroke_index, round_holes.strokes, round_holes.putts, round_holes.tee_club_id, round_holes.tee_accuracy, round_holes.first_putt_feet, round_holes.fairway_bunker, round_holes.greenside_bunker, round_holes.penalties, round_holes.penalty_type FROM round_holes
JOIN rounds ON rounds.id = round_holes.round_id
WHERE rounds.user_id = ?
ORDER BY round_holes.round_id, round_holes.hole_number
`

// Everything a backup needs, in one pass rather than a query per round.
func (q *Queries) ListAllRoundHolesByUser(ctx context.Context, userID string) ([]RoundHole, error) {
	rows, err := q.db.QueryContext(ctx, listAllRoundHolesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoundHole{}
	for rows.Next() {
		var i RoundHole
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.HoleNumber,
			&i.Par,
			&i.Yardage,
			&i.StrokeIndex,
			&i.Strokes,
			&i.Putts,
			&i.TeeClubID,
			&i.TeeAccuracy,
			&i.FirstPuttFeet,
			&i.FairwayBunker,
			&i.GreensideBunker,
			&i.Penalties,
			&i.PenaltyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRounds = `-- name: ListAllRounds :many
SELECT id, user_id, course_id, course_name, tee_id, tee_name, tee_color, course_rating, slope_rating, played_on, started_at, completed_at, status, entry_mode, holes_intended, nine, notes, created_at, updated_at FROM rounds
WHERE user_id = ?
ORDER BY played_on DESC, created_at DESC
`

func (q *Queries) ListAllRounds(ctx context.Context, userID string) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listAllRounds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Round{}
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.CourseName,
			&i.TeeID,
			&i.TeeName,
			&i.TeeColor,
			&i.CourseRating,
			&i.SlopeRating,
			&i.PlayedOn,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.EntryMode,
			&i.HolesIntended,
			&i.Nine,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoundHoles = `-- name: ListRoundHoles :many
SELECT id, round_id, hole_number, par, yardage, stroke_index, strokes, putts, tee_club_id, tee_accuracy, first_putt_feet, fairway_bunker, greenside_bunker, penalties, penalty_type FROM round_holes WHERE round_id = ? ORDER BY hole_number
`

func (q *Queries) ListRoundHoles(ctx context.Context, roundID string) ([]RoundHole, error) {
	rows, err := q.db.QueryContext(ctx, listRoundHoles, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoundHole{}
	for rows.Next() {
		var i RoundHole
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.HoleNumber,
			&i.Par,
			&i.Yardage,
			&i.StrokeIndex,
			&i.Strokes,
			&i.Putts,
			&i.TeeClubID,
			&i.TeeAccuracy,
			&i.FirstPuttFeet,
			&i.FairwayBunker,
			&i.GreensideBunker,
			&i.Penalties,
			&i.PenaltyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRounds = `-- name: ListRounds :many
SELECT id, user_id, course_id, course_name, tee_id, tee_name, tee_color, course_rating, slope_rating, played_on, started_at, completed_at, status, entry_mode, holes_intended, nine, notes, created_at, updated_at FROM rounds
WHERE user_id = ?
ORDER BY played_on DESC, created_at DESC
LIMIT ? OFFSET ?
`

type ListRoundsParams struct {
	UserID string
	Limit  int64
	Offset int64
}

func (q *Queries) ListRounds(ctx context.Context, arg ListRoundsParams) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listRounds, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Round{}
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.CourseName,
			&i.TeeID,
			&i.TeeName,
			&i.TeeColor,
			&i.CourseRating,
			&i.SlopeRating,
			&i.PlayedOn,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.EntryMode,
			&i.HolesIntended,
			&i.Nine,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoundsByStatus = `-- name: ListRoundsByStatus :many
SELECT id, user_id, course_id, course_name, tee_id, tee_name, tee_color, course_rating, slope_rating, played_on, started_at, completed_at, status, entry_mode, holes_intended, nine, notes, created_at, updated_at FROM rounds
WHERE user_id = ? AND status = ?
ORDER BY started_at DESC, created_at DESC
`

type ListRoundsByStatusParams struct {
	UserID string
	Status string
}

// Several rounds may be open at once, so this is a list rather than a lookup.
// A player who abandons one to weather and starts another the next day should
// not have to tidy up before they can play.
func (q *Queries) ListRoundsByStatus(ctx context.Context, arg ListRoundsByStatusParams) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listRoundsByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Round{}
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.CourseName,
			&i.TeeID,
			&i.TeeName,
			&i.TeeColor,
			&i.CourseRating,
			&i.SlopeRating,
			&i.PlayedOn,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.EntryMode,
			&i.HolesIntended,
			&i.Nine,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoundStatus = `-- name: SetRoundStatus :exec
UPDATE rounds
SET status = ?, completed_at = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type SetRoundStatusParams struct {
	Status      string
	CompletedAt *string
	UpdatedAt   string
	ID          string
	UserID      string
}

func (q *Queries) SetRoundStatus(ctx context.Context, arg SetRoundStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRoundStatus,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateRound = `-- name: UpdateRound :exec
UPDATE rounds
SET played_on = ?, notes = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateRoundParams struct {
	PlayedOn  string
	Notes     *string
	UpdatedAt string
	ID        string
	UserID    string
}

// Metadata only. Holes are written through their own statement so that a stale
// form cannot change something the user was not looking at.
func (q *Queries) UpdateRound(ctx context.Context, arg UpdateRoundParams) error {
	_, err := q.db.ExecContext(ctx, updateRound,
		arg.PlayedOn,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertRoundHole = `-- name: UpsertRoundHole :exec
INSERT INTO round_holes (
    id, round_id, hole_number, par, yardage, stroke_index,
    strokes, putts, tee_club_id, tee_accuracy, first_putt_feet,
    fairway_bunker, greenside_bunker, penalties, penalty_type
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(round_id, hole_number) DO UPDATE SET
    -- The snapshots are server-owned: written once when the round starts, and
    -- kept unless a value is actually supplied. COALESCE is what lets a score
    -- edit leave them alone - without it, saving a putt count would blank the
    -- par the whole statistics layer depends on. Supplying one still works,
    -- which is how a hole missing its par gets filled in mid-round.
    par = COALESCE(excluded.par, round_holes.par),
    yardage = COALESCE(excluded.yardage, round_holes.yardage),
    stroke_index = COALESCE(excluded.stroke_index, round_holes.stroke_index),
    -- The scoring fields replace outright, NULL included: this is a PUT, the
    -- payload is the whole hole, and clearing a mis-tapped score has to work.
    strokes = excluded.strokes,
    putts = excluded.putts,
    tee_club_id = excluded.tee_club_id,
    tee_accuracy = excluded.tee_accuracy,
    first_putt_feet = excluded.first_putt_feet,
    fairway_bunker = excluded.fairway_bunker,
    greenside_bunker = excluded.greenside_bunker,
    penalties = excluded.penalties,
    penalty_type = excluded.penalty_type
`

type UpsertRoundHoleParams struct {
	ID              string
	RoundID         string
	HoleNumber      int64
	Par             *int64
	Yardage         *int64
	StrokeIndex     *int64
	Strokes         *int64
	Putts           *int64
	TeeClubID       *string
	TeeAccuracy     *string
	FirstPuttFeet   *int64
	FairwayBunker   int64
	GreensideBunker int64
	Penalties       int64
	PenaltyType     *string
}

// The live path writes one of these per hole, and the manual path writes
// eighteen in a transaction. Both go through this same upsert, keyed on
// (round_id, hole_number), which is what makes a queued write safe to replay:
// the same hole sent twice is the same hole, not two.
func (q *Queries) UpsertRoundHole(ctx context.Context, arg UpsertRoundHoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoundHole,
		arg.ID,
		arg.RoundID,
		arg.HoleNumber,
		arg.Par,
		arg.Yardage,
		arg.StrokeIndex,
		arg.Strokes,
		arg.Putts,
		arg.TeeClubID,
		arg.TeeAccuracy,
		arg.FirstPuttFeet,
		arg.FairwayBunker,
		arg.GreensideBunker,
		arg.Penalties,
		arg.PenaltyType,
	)
	return err
}
