// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tees.sql

package sqlc

import (
	"context"
)

const createTee = `-- name: CreateTee :exec
INSERT INTO tees (
    id, course_id, name, color,
    course_rating_men, slope_rating_men, course_rating_women, slope_rating_women,
    front9_course_rating_men, front9_slope_rating_men, back9_course_rating_men, back9_slope_rating_men,
    front9_course_rating_women, front9_slope_rating_women, back9_course_rating_women, back9_slope_rating_women,
    total_yardage, display_order
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTeeParams struct {
	ID                      string
	CourseID                string
	Name                    string
	Color                   string
	CourseRatingMen         *float64
	SlopeRatingMen          *int64
	CourseRatingWomen       *float64
	SlopeRatingWomen        *int64
	Front9CourseRatingMen   *float64
	Front9SlopeRatingMen    *int64
	Back9CourseRatingMen    *float64
	Back9SlopeRatingMen     *int64
	Front9CourseRatingWomen *float64
	Front9SlopeRatingWomen  *int64
	Back9CourseRatingWomen  *float64
	Back9SlopeRatingWomen   *int64
	TotalYardage            *int64
	DisplayOrder            int64
}

func (q *Queries) CreateTee(ctx context.Context, arg CreateTeeParams) error {
	_, err := q.db.ExecContext(ctx, createTee,
		arg.ID,
		arg.CourseID,
		arg.Name,
		arg.Color,
		arg.CourseRatingMen,
		arg.SlopeRatingMen,
		arg.CourseRatingWomen,
		arg.SlopeRatingWomen,
		arg.Front9CourseRatingMen,
		arg.Front9SlopeRatingMen,
		arg.Back9CourseRatingMen,
		arg.Back9SlopeRatingMen,
		arg.Front9CourseRatingWomen,
		arg.Front9SlopeRatingWomen,
		arg.Back9CourseRatingWomen,
		arg.Back9SlopeRatingWomen,
		arg.TotalYardage,
		arg.DisplayOrder,
	)
	return err
}

const deleteTee = `-- name: DeleteTee :exec
DELETE FROM tees WHERE id = ?
`

func (q *Queries) DeleteTee(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTee, id)
	return err
}

const getTee = `-- name: GetTee :one
SELECT id, course_id, name, color, course_rating_men, slope_rating_men, total_yardage, display_order, course_rating_women, slope_rating_women, front9_course_rating_men, front9_slope_rating_men, back9_course_rating_men, back9_slope_rating_men, front9_course_rating_women, front9_slope_rating_women, back9_course_rating_women, back9_slope_rating_women FROM tees WHERE id = ?
`

func (q *Queries) GetTee(ctx context.Context, id string) (Tee, error) {
	row := q.db.QueryRowContext(ctx, getTee, id)
	var i Tee
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Color,
		&i.CourseRatingMen,
		&i.SlopeRatingMen,
		&i.TotalYardage,
		&i.DisplayOrder,
		&i.CourseRatingWomen,
		&i.SlopeRatingWomen,
		&i.Front9CourseRatingMen,
		&i.Front9SlopeRatingMen,
		&i.Back9CourseRatingMen,
		&i.Back9SlopeRatingMen,
		&i.Front9CourseRatingWomen,
		&i.Front9SlopeRatingWomen,
		&i.Back9CourseRatingWomen,
		&i.Back9SlopeRatingWomen,
	)
	return i, err
}

const listTeesByCourse = `-- name: ListTeesByCourse :many
SELECT id, course_id, name, color, course_rating_men, slope_rating_men, total_yardage, display_order, course_rating_women, slope_rating_women, front9_course_rating_men, front9_slope_rating_men, back9_course_rating_men, back9_slope_rating_men, front9_course_rating_women, front9_slope_rating_women, back9_course_rating_women, back9_slope_rating_women FROM tees WHERE course_id = ? ORDER BY display_order ASC, name COLLATE NOCASE ASC
`

func (q *Queries) ListTeesByCourse(ctx context.Context, courseID string) ([]Tee, error) {
	rows, err := q.db.QueryContext(ctx, listTeesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tee{}
	for rows.Next() {
		var i Tee
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.Color,
			&i.CourseRatingMen,
			&i.SlopeRatingMen,
			&i.TotalYardage,
			&i.DisplayOrder,
			&i.CourseRatingWomen,
			&i.SlopeRatingWomen,
			&i.Front9CourseRatingMen,
			&i.Front9SlopeRatingMen,
			&i.Back9CourseRatingMen,
			&i.Back9SlopeRatingMen,
			&i.Front9CourseRatingWomen,
			&i.Front9SlopeRatingWomen,
			&i.Back9CourseRatingWomen,
			&i.Back9SlopeRatingWomen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTeeDisplayOrder = `-- name: MaxTeeDisplayOrder :one
SELECT CAST(IFNULL(MAX(display_order), -1) AS INTEGER) AS max_order FROM tees WHERE course_id = ?
`

func (q *Queries) MaxTeeDisplayOrder(ctx context.Context, courseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTeeDisplayOrder, courseID)
	var max_order int64
	err := row.Scan(&max_order)
	return max_order, err
}

const updateTee = `-- name: UpdateTee :exec
UPDATE tees
SET name = ?, color = ?,
    course_rating_men = ?, slope_rating_men = ?, course_rating_women = ?, slope_rating_women = ?,
    front9_course_rating_men = ?, front9_slope_rating_men = ?, back9_course_rating_men = ?, back9_slope_rating_men = ?,
    front9_course_rating_women = ?, front9_slope_rating_women = ?, back9_course_rating_women = ?, back9_slope_rating_women = ?,
    total_yardage = ?, display_order = ?
WHERE id = ?
`

type UpdateTeeParams struct {
	Name                    string
	Color                   string
	CourseRatingMen         *float64
	SlopeRatingMen          *int64
	CourseRatingWomen       *float64
	SlopeRatingWomen        *int64
	Front9CourseRatingMen   *float64
	Front9SlopeRatingMen    *int64
	Back9CourseRatingMen    *float64
	Back9SlopeRatingMen     *int64
	Front9CourseRatingWomen *float64
	Front9SlopeRatingWomen  *int64
	Back9CourseRatingWomen  *float64
	Back9SlopeRatingWomen   *int64
	TotalYardage            *int64
	DisplayOrder            int64
	ID                      string
}

func (q *Queries) UpdateTee(ctx context.Context, arg UpdateTeeParams) error {
	_, err := q.db.ExecContext(ctx, updateTee,
		arg.Name,
		arg.Color,
		arg.CourseRatingMen,
		arg.SlopeRatingMen,
		arg.CourseRatingWomen,
		arg.SlopeRatingWomen,
		arg.Front9CourseRatingMen,
		arg.Front9SlopeRatingMen,
		arg.Back9CourseRatingMen,
		arg.Back9SlopeRatingMen,
		arg.Front9CourseRatingWomen,
		arg.Front9SlopeRatingWomen,
		arg.Back9CourseRatingWomen,
		arg.Back9SlopeRatingWomen,
		arg.TotalYardage,
		arg.DisplayOrder,
		arg.ID,
	)
	return err
}
