// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trusted_devices.sql

package sqlc

import (
	"context"
)

const createTrustedDevice = `-- name: CreateTrustedDevice :exec
INSERT INTO trusted_devices (id, user_id, token_hash, label, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTrustedDeviceParams struct {
	ID        string
	UserID    string
	TokenHash string
	Label     *string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) CreateTrustedDevice(ctx context.Context, arg CreateTrustedDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createTrustedDevice,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Label,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAllTrustedDevices = `-- name: DeleteAllTrustedDevices :exec
DELETE FROM trusted_devices WHERE user_id = ?
`

// Used whenever the account's credentials change and whenever two-factor is
// switched off: trust granted under the old password should not survive it.
func (q *Queries) DeleteAllTrustedDevices(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllTrustedDevices, userID)
	return err
}

const deleteExpiredTrustedDevices = `-- name: DeleteExpiredTrustedDevices :exec
DELETE FROM trusted_devices WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredTrustedDevices(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTrustedDevices, expiresAt)
	return err
}

const deleteTrustedDevice = `-- name: DeleteTrustedDevice :exec
DELETE FROM trusted_devices WHERE id = ? AND user_id = ?
`

type DeleteTrustedDeviceParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteTrustedDevice(ctx context.Context, arg DeleteTrustedDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteTrustedDevice, arg.ID, arg.UserID)
	return err
}

const getTrustedDevice = `-- name: GetTrustedDevice :one
SELECT id, user_id, token_hash, label, expires_at, created_at, last_used_at FROM trusted_devices
WHERE token_hash = ? AND user_id = ? AND expires_at > ?
`

type GetTrustedDeviceParams struct {
	TokenHash string
	UserID    string
	ExpiresAt string
}

// Scoped to the user as well as the hash. The token is unguessable on its own,
// but a lookup that ignores the user would let one account's device token
// satisfy another account's challenge if a hash ever collided or leaked.
func (q *Queries) GetTrustedDevice(ctx context.Context, arg GetTrustedDeviceParams) (TrustedDevice, error) {
	row := q.db.QueryRowContext(ctx, getTrustedDevice, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Label,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listTrustedDevices = `-- name: ListTrustedDevices :many
SELECT id, user_id, token_hash, label, expires_at, created_at, last_used_at FROM trusted_devices
WHERE user_id = ? AND expires_at > ?
ORDER BY created_at DESC
`

type ListTrustedDevicesParams struct {
	UserID    string
	ExpiresAt string
}

func (q *Queries) ListTrustedDevices(ctx context.Context, arg ListTrustedDevicesParams) ([]TrustedDevice, error) {
	rows, err := q.db.QueryContext(ctx, listTrustedDevices, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustedDevice{}
	for rows.Next() {
		var i TrustedDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Label,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTrustedDevice = `-- name: TouchTrustedDevice :exec
UPDATE trusted_devices SET last_used_at = ? WHERE id = ?
`

type TouchTrustedDeviceParams struct {
	LastUsedAt *string
	ID         string
}

func (q *Queries) TouchTrustedDevice(ctx context.Context, arg TouchTrustedDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchTrustedDevice, arg.LastUsedAt, arg.ID)
	return err
}
