// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash, display_name, email_verified, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID            string
	Email         string
	PasswordHash  *string
	DisplayName   string
	EmailVerified int64
	CreatedAt     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmailVerified,
		arg.CreatedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, email_verified, created_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, email_verified, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users SET email_verified = ? WHERE id = ?
`

type SetUserEmailVerifiedParams struct {
	EmailVerified int64
	ID            string
}

func (q *Queries) SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, setUserEmailVerified, arg.EmailVerified, arg.ID)
	return err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordHashParams struct {
	PasswordHash *string
	ID           string
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, setUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = ? WHERE id = ?
`

type UpdateUserDisplayNameParams struct {
	DisplayName string
	ID          string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}
